### ISSUE TITLE
Write contribution guides

### ISSUE THREAD

**Issue by esoubiran-aneo** [aneoconsulting/ArmoniK#1025]
- [ ] https://github.com/aneoconsulting/ArmoniK.Community/issues/6
- [ ] https://github.com/aneoconsulting/ArmoniK.Community/issues/8
- [ ] https://github.com/aneoconsulting/ArmoniK.Community/issues/5
- [ ] https://github.com/aneoconsulting/ArmoniK.Community/issues/7
- [ ] https://github.com/aneoconsulting/ArmoniK.Community/issues/4
