### ISSUE TITLE
Bugs fixing

### ISSUE THREAD

**Issue by esoubiran-aneo** [aneoconsulting/ArmoniK#283]
- [x] [fix: update title size](https://github.com/aneoconsulting/ArmoniK.Admin.GUI/issues/92)
- [x] [fix sorting in sessions and tasks table](https://github.com/aneoconsulting/ArmoniK.Admin.GUI/issues/88)
- [x] [fix "see-more" on tasks table](https://github.com/aneoconsulting/ArmoniK.Admin.GUI/issues/87)
- [x] [fix: french translation](https://github.com/aneoconsulting/ArmoniK.Admin.GUI/issues/86)
- [x] [fix: add a working loading on tasks table ](https://github.com/aneoconsulting/ArmoniK.Admin.GUI/pull/93)
- [x] [fix: missing status on sessions table](https://github.com/aneoconsulting/ArmoniK.Admin.GUI/pull/99)
- [x] [fix: handle more status for tasks](https://github.com/aneoconsulting/ArmoniK.Admin.GUI/pull/100)
- [x] [fix: remove useless dash](https://github.com/aneoconsulting/ArmoniK.Admin.GUI/pull/102)
- [x] [fix: tasks sorting on status doesn't work](https://github.com/aneoconsulting/ArmoniK.Admin.GUI/pull/104)
- [x] [fix: order with title and errors](https://github.com/aneoconsulting/ArmoniK.Admin.GUI/pull/105)
- [x] [fix: cancelled to canceled](https://github.com/aneoconsulting/ArmoniK.Admin.GUI/pull/106)
- [x] [fix: disabled selection when tasks is completed](https://github.com/aneoconsulting/ArmoniK.Admin.GUI/pull/107)
- [x] [fix: use status instead of date to cancel session](https://github.com/aneoconsulting/ArmoniK.Admin.GUI/pull/108)
- [x] [fix: can cancel only one session](https://github.com/aneoconsulting/ArmoniK.Admin.GUI/pull/109)
