### ISSUE TITLE
Extension.Csharp refactoring

### ISSUE THREAD

**Issue by dbrasseur-aneo** [aneoconsulting/ArmoniK#536]
Extension.Csharp is in a dire need of a refactoring, to simplify and refresh its design, to reduce technical debt accumulation, to reduce repetition and to improve both its reliability and performance. This issue tracks the steps of this refactoring.

**Reorganisation and simplification:**
- [ ] Extension.Csharp projects reorganization
- [ ] Extension.Csharp populate commons with common classes
- [ ] Extension.Csharp reduce repetition
- [ ] ...

**Technical debt reduction:**
- [ ] #471 
- [ ] ...

**Reliability:**
- [ ] Extension.Csharp Add unit tests to Clients
- [ ] Extension.Csharp Add unit tests to Workers
- [ ] Extension.Csharp Add unit tests to Common
- [ ] ...

**Performance:**
- [ ] Extension.Csharp Assess and profile performance difference between the native API and ExtC#
- [ ] ...
