### ISSUE TITLE
Improve UX of GUI 💅

### ISSUE THREAD

**Issue by esoubiran-aneo** [aneoconsulting/ArmoniK#585]
## gRPC
- [ ] Create endpoint to list application name
- [ ] Create endpoint to list application version
- [ ] Add count of tasks in a session
- [ ] Add last activity in a session

## Sidebar
- [x] #607
- [x] #598
- [x] #608
- [x] #602
- [x] #604
- [x] Fix glitch in sidebar when nav group open

## Applications
- [ ] Allow click on tasks status to view corresponding tasks
- [ ] Add the count tasks by status
- [ ] Add a refresh button

### Errors
- [ ] Add filter on application name
- [ ] Add filter on application version
- [ ] Add filter on session id (use like) (or not, need advice)
- [ ] Add filter on error at (before and after)
- [ ] Allow a click on error message to view full message
- [ ] Rename "link to seq" to "actions"

## Sessions
- [ ] Add the count tasks by status in a session
- [ ] Add icon in refresh button
- [ ] Rework auto refresh to simplify use
- [x] #665
- [x] Add filter on count tasks
- [x] Add filter on created at (before and after)
- [x] Add filter on cancelled at (before and after)
- [x] Add filter on last activity at (before and after)
- [ ] Cancellation date is useless

## Task
- [ ] Show pod name
- [ ] Add a copy to clipboard for pod name
- [ ] Add filtering on duration
- [ ] Remove some status from filters
- [ ] Easily find retries
- [ ] Get number of retries
- [ ] Link to Seq without level
- [ ] Link to Seq with taskid
- [ ] Link to Seq using 'like' to view retries

## Table
- [ ] #600
- [ ] Add auto-refresh state in URL
- [ ] Use query params to setup default sorting values
- [ ] Add more title to explain buttons

## Modal
- [ ] Use URL to handle modal state

## Docs
- [x] Add a section to explain "add to favorites"

## Others
- [x] #633

## Triage required
Count erreurs and errors on retry
dans la liste des sessions, il peut y avoir status erreurs alors que c'est des retry
Avoir la possiblité d'ajouter des champs custom dans la table depuis des champs custom des tasks options
Add more tips

**Comment by esoubiran-aneo** [comment]
Will close this because the GUI change a lot since we created this issue. Our next focus will be on the UX of the GUI.
