### ISSUE TITLE
Development of Unit test in Armonik.Core 

### ISSUE THREAD

**Issue by ddubuc** [aneoconsulting/ArmoniK#75]
Implement unit tests for ArmoniK.Core:

- [x] IResulTable table (closed via aneoconsulting/ArmoniK.Core#5)
- [x] ITask table (solved via   aneoconsulting/ArmoniK.Core#7)
- [x] IDispatch table (aneoconsulting/ArmoniK.Core#11)
- [x] ISession table  (aneoconsulting/ArmoniK.Core#14)

**Comment by jfonseca-aneo** [comment]
The tests for ResultTable for the MongoDB and memory interfaces are implemented. Next step: tests for Task, Session and Dispatch tables
