### ISSUE TITLE
GUI fixes and refactors

### ISSUE THREAD

**Issue by Faust1-2was-Aneo** [aneoconsulting/ArmoniK#827]
- [x] [ArmoniK.Api.GUI#399](https://github.com/aneoconsulting/ArmoniK.Admin.GUI/issues/399)
- [x] [ArmoniK.Api.GUI#404](https://github.com/aneoconsulting/ArmoniK.Admin.GUI/issues/404)
- [x] [ArmoniK.Api.GUI#407](https://github.com/aneoconsulting/ArmoniK.Admin.GUI/issues/407)
- [x] [ArmoniK.Api.GUI#409](https://github.com/aneoconsulting/ArmoniK.Admin.GUI/issues/409)
- [x] [ArmoniK.apu.GUI#412](https://github.com/aneoconsulting/ArmoniK.Admin.GUI/issues/412)
- [x] [ArmoniK.apu.GUI#414](https://github.com/aneoconsulting/ArmoniK.Admin.GUI/issues/414)
- [x] [ArmoniK.apu.GUI#416](https://github.com/aneoconsulting/ArmoniK.Admin.GUI/issues/416)
