### ISSUE TITLE
Create an armonik Cluster & Deploy Armonik

### ISSUE THREAD

**Issue by alouvion-aneo** [aneoconsulting/ArmoniK#996]
- [x] terraform script to deploy EC2 on AWS
- [x] given a list of machine ips and keys install kubernetes on it
- [x] given a kubernetes environment, install a fully functional armonik (similar to on prem install - cloud agnostic )
- [x] #1040 
- [x] #1047
- [ ] #1071
